/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package studentportal;

/**
 *
 * @author User
 */

import java.sql.*;

public class count extends javax.swing.JFrame {

    /**
     * Creates new form count
     */
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public count() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        namelike = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        center_s = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        vaccine_s = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        nurse_s = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        namelike_s = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        center = new javax.swing.JLabel();
        vaccine = new javax.swing.JLabel();
        nurse = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(54, 33, 89));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        namelike.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        namelike.setForeground(new java.awt.Color(255, 255, 255));
        namelike.setText("0");
        jPanel2.add(namelike, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 130, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 280, 10));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 10, 60));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/icons8-cancel-30.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/home2.png"))); // NOI18N
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 10, -1, -1));

        center_s.setBackground(new java.awt.Color(54, 33, 89));
        center_s.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        center_s.setForeground(new java.awt.Color(255, 255, 255));
        center_s.setText("By Center");
        center_s.setBorder(null);
        center_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                center_sActionPerformed(evt);
            }
        });
        jPanel2.add(center_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 140, 20));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 230, 20));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/search 2.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, -1, -1));

        vaccine_s.setBackground(new java.awt.Color(54, 33, 89));
        vaccine_s.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        vaccine_s.setForeground(new java.awt.Color(255, 255, 255));
        vaccine_s.setText("By Vaccine");
        vaccine_s.setBorder(null);
        vaccine_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vaccine_sActionPerformed(evt);
            }
        });
        jPanel2.add(vaccine_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 140, 20));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 230, 20));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/search 2.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        nurse_s.setBackground(new java.awt.Color(54, 33, 89));
        nurse_s.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        nurse_s.setForeground(new java.awt.Color(255, 255, 255));
        nurse_s.setText("By Nurse");
        nurse_s.setBorder(null);
        nurse_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nurse_sActionPerformed(evt);
            }
        });
        jPanel2.add(nurse_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 140, 20));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 230, 20));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/search 2.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 290, -1, -1));

        namelike_s.setBackground(new java.awt.Color(54, 33, 89));
        namelike_s.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        namelike_s.setForeground(new java.awt.Color(255, 255, 255));
        namelike_s.setText("By Namelike");
        namelike_s.setBorder(null);
        namelike_s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namelike_sActionPerformed(evt);
            }
        });
        jPanel2.add(namelike_s, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 140, 20));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 410, 230, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/search 2.png"))); // NOI18N
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/arrow.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/arrow.png"))); // NOI18N
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/arrow.png"))); // NOI18N
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studentportal/arrow.png"))); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Count");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 60, -1));

        center.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        center.setForeground(new java.awt.Color(255, 255, 255));
        center.setText("0");
        jPanel2.add(center, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 130, 130, -1));

        vaccine.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        vaccine.setForeground(new java.awt.Color(255, 255, 255));
        vaccine.setText("0");
        jPanel2.add(vaccine, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 130, -1));

        nurse.setFont(new java.awt.Font("Tempus Sans ITC", 1, 36)); // NOI18N
        nurse.setForeground(new java.awt.Color(255, 255, 255));
        nurse.setText("0");
        jPanel2.add(nurse, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 850, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel5MouseClicked

    private void center_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_center_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_center_sActionPerformed

    private void vaccine_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vaccine_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vaccine_sActionPerformed

    private void nurse_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nurse_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nurse_sActionPerformed

    private void namelike_sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namelike_sActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namelike_sActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
         try{

            con = DriverManager.getConnection("jdbc:mysql://localhost/uni_portal","root","");
            String sql = "select count(reg_number) as jihad from vaccine GROUP by vaccine_center_id having vaccine_center_id=?";
            pst = con.prepareStatement(sql);
            
            pst.setString(1,center_s.getText());
            rs = pst.executeQuery();      
            
            rs.next();
            
            int cen = rs.getInt("jihad");
            
            center.setText(Integer.toString(cen));
            
            
         con.close();
        }
        catch(SQLException ex){
            System.out.print(ex);
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        
         try{

            con = DriverManager.getConnection("jdbc:mysql://localhost/uni_portal","root","");
            String sql = "select count(reg_number) as jihad from first_dose GROUP by vaccine_name having vaccine_name=? ";
            pst = con.prepareStatement(sql);
            
            pst.setString(1,vaccine_s.getText());
            rs = pst.executeQuery();      
            
            rs.next();
            
            int cen = rs.getInt("jihad");
            
            vaccine.setText(Integer.toString(cen));
            
            
         con.close();
        }
        catch(SQLException ex){
            System.out.print(ex);
        }
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        try{

            con = DriverManager.getConnection("jdbc:mysql://localhost/uni_portal","root","");
            String sql = "select count(reg_number) as jihad from first_dose GROUP by nurse_name having nurse_name=? ";
            pst = con.prepareStatement(sql);
            
            pst.setString(1,nurse_s.getText());
            rs = pst.executeQuery();      
            
            rs.next();
            
            int cen = rs.getInt("jihad");
            
            nurse.setText(Integer.toString(cen));
            
            
         con.close();
        }
        catch(SQLException ex){
            System.out.print(ex);
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(count.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new count().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel center;
    private javax.swing.JTextField center_s;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel namelike;
    private javax.swing.JTextField namelike_s;
    private javax.swing.JLabel nurse;
    private javax.swing.JTextField nurse_s;
    private javax.swing.JLabel vaccine;
    private javax.swing.JTextField vaccine_s;
    // End of variables declaration//GEN-END:variables
}
